development:
  adapter: postgresql
  database: hotplate_development
  user: root
  password:
  timeout: 5000

test: &test
  adapter: postgresql
  database: hotplate_test
  user: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hotplate_production
  user: root
  password:
  pool: 5
  timeout: 5000

cucumber:
  <<: *test